BEGIN TRANSACTION;


DROP TABLE Devices;
DROP TABLE Types;
DROP TABLE PTM330States;
DROP TABLE DimmerStates;

-- Typ of action (on, off , toggle)
CREATE TABLE Devices (
  Id INTEGER PRIMARY KEY,
  TypeId INTEGER,
  Name TEXT);

CREATE TABLE Types (
  Id INTEGER PRIMARY KEY,
  Name TEXT);

CREATE TABLE PTM330States (
  Id INTEGER PRIMARY KEY,
  Up INTEGER);

CREATE TABLE DimmerStates (
  Id INTEGER PRIMARY KEY,
  LightsOn INTEGER,
  DimValue INTEGER);

INSERT INTO Devices VALUES(8609771, 3, "Demo PTM330");
INSERT INTO Devices VALUES(2422779, 1, "Baderoms Bryter");
INSERT INTO Devices VALUES(8705091, 2, "Baderoms Dimmer");

INSERT INTO Types VALUES(1,'FT55-rw');
INSERT INTO Types VALUES(2,'FUD61NPN-230V');
INSERT INTO Types VALUES(3,'PTM330');

INSERT INTO PTM330States VALUES(8609771, NULL);

INSERT INTO DimmerStates VALUES(8705091, NULL, NULL);

COMMIT;

